# Generated by Django 6.0.4 on 2026-05-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(max_length=50, verbose_name='Menu Type')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Restaurant Name')),
                ('address', models.CharField(max_length=255, verbose_name='Restaurant Address')),
                ('photo', models.ImageField(height_field=512, upload_to='', width_field=512)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Restaurant Latitude')),
                ('longditude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Restaurant Longditude')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restaurants.restaurantmenutype')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('comment_text', models.TextField(verbose_name='Review Details')),
                ('for_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['comment_text'], name='comments_text_index')],
            },
        ),
    ]
