# Generated by Django 6.0.4 on 2026-06-01 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(height_field='512', upload_to='', width_field='512'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('name', 'address', 'latitude', 'longditude')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('for_restaurant', 'created_by')},
        ),
    ]
