# Generated by Django 6.0.4 on 2026-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_created_by_review_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenutype',
            name='menu_type',
            field=models.CharField(max_length=50, unique=True, verbose_name='Menu Type'),
        ),
    ]
