# Generated by Django 6.0.4 on 2026-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_text',
            field=models.TextField(blank=True, verbose_name='Review Details'),
        ),
    ]
